language: java

jdk:
  - openjdk8

install:
  - mvn test-compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V

after_success:
  - mvn clean test cobertura:cobertura jacoco:report coveralls:report

# Deploy Github pages after success of Java Tests.
deploy:
  provider: pages
  skip_cleanup: true
  keep-history: false
  target-branch: gh-pages
  github_token: "$GITHUB_TOKEN"
  local_dir: "./target/generated-docs"
  on:
    branch: sprint7-91-tests
