name: GHPages

on:
  push:
    branches:
      - $default_branch

  workflow_dispatch:

jobs:
  ghpages:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: "Maven Cache"
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-cache-maven-${{ hashFiles('**/pom.xml') }}

      - name: "Setup Java"
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: "Maven Test"
        run: mvn clean test cobertura:cobertura jacoco:report coveralls:report -DdryRun=true

      - name: "Deploy GH-Pages"
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          github_token: ${{ secrets.github_token }}
          branch: gh-pages
          folder: target/generated-docs
          clean: true
          single_commit: true
